and that piece of art is useful - Dora Korpar, 2015-10-19
Traceback (most recent call last):
  File "./100-write.py", line 4, in <module>
    sys.exist(1)
AttributeError: module 'sys' has no attribute 'exist'
